name: Lambda Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*
    paths:
      - 'AWSSamples.Lambda/AWSSamples.Lambda.Web/**'
      - '.github/workflows/lambda_deploy_function.yml'


jobs:
  buildandtest:
    name: Build And Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: AWSSamples.Lambda/AWSSamples.Lambda.Web
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

  #         TODO: Write some example tests
  #      - name: Test
  #        run: dotnet test --no-build --verbosity normal

  deploy:
    name: Deploy Function
    runs-on: ubuntu-latest
    needs: [ buildandtest ]
    defaults:
      run:
        working-directory: AWSSamples.Lambda/AWSSamples.Lambda.Web
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Install Dotnet CLI Lambda Tools
        run: dotnet tool install -g Amazon.Lambda.Tools

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy Function to AWS
        run: dotnet lambda deploy-function aws-samples-test-function --function-role iam_for_lambda
