name: Pulumi - Lambda - Preview

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'AWSSamples.Lambda/AWSSamples.Lambda.Infrastructure/**'
      - '.github/workflows/pulumi_preview_lambda.yml'
  push:
    branches:
      - dev
    paths:
      - 'AWSSamples.Lambda/AWSSamples.Lambda.Infrastructure/**'
      - '.github/workflows/pulumi_preview_lambda.yml'

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: ${{ secrets.PULUMI_ORG }}/aws-samples/lambdas
          work-dir: ./AWSSamples.Lambda/AWSSamples.Lambda.Infrastructure
          config-map: "{
            functionName: {value: aws-samples-test-function, secret: false},
            emails: {value: ${{ secrets.BUDGET_EMAILS }}, secret: false},
            domain: {value: ${{ secrets.DOMAIN }}, secret: false}
          }"
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}