name: Pulumi - Lambda

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'AWSSamples.Lambda/AWSSamples.Lambda.Infrastructure/**'
      - '.github/workflows/pulumi_deployment_lambda.yml'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x  

      - name: Publish Web API to have a Zip to upload to S3 on creation
        run: dotnet publish
        working-directory: AWSSamples.Lambda/AWSSamples.Lambda.Web

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: ${{ secrets.PULUMI_ORG }}/aws-samples/lambdas
          work-dir: ./AWSSamples.Lambda/AWSSamples.Lambda.Infrastructure
          config-map: "{
            domain: {value: ${{ secrets.DOMAIN }}, secret: false}
          }"
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}