name: Pulumi - S3 Blazor

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'AWSSamples.S3/AWSSamples.S3.Infrastructure/**'
      - '.github/workflows/pulumi_deployment_s3blazor.yml'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x  

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: ${{ secrets.PULUMI_ORG }}/aws-samples/s3-blazor
          work-dir: ./AWSSamples.S3/AWSSamples.S3.Infrastructure
          config-map: "{
            emails: {value: ${{ secrets.BUDGET_EMAILS }}, secret: false},
            domain: {value: ${{ secrets.DOMAIN }}, secret: false},
          }"
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}